- platform: template
  sensors:
    garage_door_opener:
      unique_id: baa6e0e0-f00f-477b-9291-885231803491
      friendly_name: "Garage Door Opener"
      device_class: garage_door
      value_template: "{{ states('cover.garage_door_opener')=='open' }}"