---
repos:
  - repo: https://github.com/Tacto-Technology/ensure-sops
    rev: 0.1.3
    hooks:
      - id: ensure-sops
        files: 'secrets.yaml'
        # type: 'yaml'
        # exclude: 'decrypted/.+'
