---
creation_rules:
  - age: age1x2at6wwq2gks47fsep9a25emdeqd93e3k0gfsswtmhruqrteu5jqjvy7kd
    encrypted_suffix: 'environment'
    path_regex: 'compose.yaml'
  - age: age1x2at6wwq2gks47fsep9a25emdeqd93e3k0gfsswtmhruqrteu5jqjvy7kd
