---
version: '3'

tasks:
  restart:
    desc: restart Docker containers
    cmds:
      - "docker compose restart"
  up:
    desc: run Docker compose in the foreground.
    cmds:
      - docker compose up
  up-d:
    desc: Run Docker compose in the background.
    cmds:
      - docker compose up -d
  ps:
    desc: List all running Docker images.
    cmds:
      - docker ps
  default:
    cmds:
      - task -l
    silent: true
