---
version: '3'

# docker run --rm -v "${PWD}":/workdir mikefarah/yq e compose.yaml

tasks:
  chown:
    desc: chown mosquitto
    cmds:
      - sudo chown -R nicholas:nicholas mosquitto/
  show-pub-key:
    desc: Show public age key
    cmds:
      - "cat ~/.config/sops/age/keys.txt | grep \"public key\" | awk \'{split($0,a,\": \"); print a[2]}\'"
    silent: true
  update:
    desc: Update running containers
    cmds:
      - docker compose up --force-recreate --build -d
      - docker image prune -f
  hacs:
    desc: Install HACS
    dir: '{{.USER_WORKING_DIR}}/ha'
    cmds:
      - wget -O - https://get.hacs.xyz | bash -
  node-red:
    desc: Prereqs for node red
    cmds:
      - npm install node-red-contrib-home-assistant-websocket
  bootstrap:
    desc: Bootstrap
    cmds:
      - test -d ~/.config/sops/age || mkdir -p ~/.config/sops/age
      - test -f ~/.config/sops/age || lpass show sops-age --attach=att-2571789250549588435-38084 -q > ~/.config/sops/age/keys.txt
      - task: dec
      - task: hacs
  enc:
    desc: Encrypt secret files
    cmds:
      - sops -e ./ha/secrets.yaml > ./ha/secrets.yaml.enc
      - sops -e ./ha/html5_push_registrations.conf > ./ha/html5_push_registrations.conf.enc
      - sops -e ./esphome/secrets.yaml > ./esphome/secrets.yaml.enc
      - sops -e ./.env > ./.env.enc
    ignore_error: true
  dec:
    desc: Decrypt secret files
    cmds:
      - git restore ./ha/secrets.yaml ./ha/html5_push_registrations.conf ./esphome/secrets.yaml ./.env
      - git pull origin
      - sops -d --input-type yaml --output-type yaml ./ha/secrets.yaml.enc > ./ha/secrets.yaml
      - sops -d ./ha/html5_push_registrations.conf.enc > ./ha/html5_push_registrations.conf
      - sops -d --input-type yaml --output-type yaml ./esphome/secrets.yaml.enc > ./esphome/secrets.yaml
      - sops -d --input-type dotenv --output-type dotenv ./.env.enc > ./.env
    ignore_error: true
  ps:
    desc: List only relevant containers
    cmds:
      - docker ps -a -f name=^/esphome$ -f name=^/homeassistant$ -f name=^/wyze-bridge$ -f name=^/node-red$
  pull:
    desc: Pull service images
    cmds:
      - docker compose pull
  stop:
    desc: Stop services
    cmds:
      - docker compose stop
  down:
    desc: Stop and remove containers, networks
    cmds:
      - docker compose down
  bash-esphome:
    desc: Open a bash inside of ESPHome container
    cmds:
      - docker exec -it esphome bash
  bash-ha:
    desc: Open a bash inside of HA container
    cmds:
      - docker exec -it homeassistant bash
  bash-wyze-bridge:
    desc: Open a bash inside of wyze-bridge container
    cmds:
      - docker exec -it wyze-bridge bash
  restart:
    desc: Restart Docker containers
    cmds:
      - "docker compose restart"
  up:
    desc: Tun Docker compose in the foreground.
    cmds:
      - docker compose up
  up-d:
    desc: Run Docker compose in the background.
    cmds:
      - docker compose up -d
  default:
    cmds:
      - task -l
    silent: true
