---
version: '3'

# docker run --rm -v "${PWD}":/workdir mikefarah/yq e compose.yaml

tasks:
  bootstrap:
    desc: Bootstrap
    cmds:
      - mkdir -d ~/.config/sops/age
      - lpass show sops-age --attach=att-2571789250549588435-38084 -q > ~/.config/sops/age/keys.txt
      - task: dec
  enc:
    desc: Encrypt compose.yaml
    cmds:
      - sops -e -i compose.yaml
  dec:
    desc: Decrypt compose.yaml
    cmds:
      - sops -d -i compose.yaml
  ps:
    desc: List only relevant containers
    cmds:
      - docker ps -a -f name=^/esphome$ -f name=^/homeassistant$
  pull:
    desc: Pull service images
    cmds:
      - docker compose pull
  stop:
    desc: Stop services
    cmds:
      - docker compose stop
  down:
    desc: Stop and remove containers, networks
    cmds:
      - docker compose down
  bash-esphome:
    desc: Open a bash inside of ESPHome container
    cmds:
      - docker exec -it esphome bash
  bash-ha:
    desc: Open a bash inside of HA container
    cmds:
      - docker exec -it homeassistant bash
  restart:
    desc: restart Docker containers
    cmds:
      - "docker compose restart"
  up:
    desc: run Docker compose in the foreground.
    cmds:
      - docker compose up
  up-d:
    desc: Run Docker compose in the background.
    cmds:
      - docker compose up -d
  default:
    cmds:
      - task -l
    silent: true
