---
esphome:
  name: esphome-web-f0880c
  friendly_name: ESPHome Web f0880c

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "DxbhV8r4mIgudoB6yrfN5pYu4J1w6Eo9TdqLojHuZns="

ota:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: ""

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-F0880C"
    password: "vHWBZPaoInye"

captive_portal:
    