#ENC[AES256_GCM,data:L+s07Q4TqvqIuv3jNGv1hBRbrdk9CGkg2oCI1Mo=,iv:cl36fiCYD68h/JghO/QTQMxfHNsp40Obnp/hxbATqRA=,tag:NZ/33xKOWty+mQkI2U7QDg==,type:comment]
wifi_ssid: ENC[AES256_GCM,data:W4zK,iv:QuXReuq/t7gz0m+9HapzZh7kXiI7Dgb0BWCs5mHm/v0=,tag:/S7s8PkVRIgfyd3uOlbhMg==,type:str]
wifi_password: ENC[AES256_GCM,data:YV9yGxqrlJHVXDGX9O37aA==,iv:o948HbxtC7nhoKtij5wCmzC4JX0z0RzcV2h1FjpD2IQ=,tag:SL4N+sYdVbOCgxlBw3LhgQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x2at6wwq2gks47fsep9a25emdeqd93e3k0gfsswtmhruqrteu5jqjvy7kd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZMFZHdU1TMWlpbnh0cjZh
            cEhjYXBZemtOR3VGbUI4YWZvVzVCT1lLSjAwCm5qOGdnOE9nZjJEQ3UvaFVaaTNo
            WmltZ0pCQlBRTGlidFlWaGNJd25Mc1UKLS0tIG9oK1VGclp6OXMvZU1ZaGg0Mitj
            SjhCY1dTNzhLTDI2QVJNRFcxYjFRMFEKRafmG24XJYyO5feJY4kwKp3knJBiRnKY
            uLmc3ranpBE0k/49+tel6/K5ORlpDH+agxQ5wM22PHv+0q6ytgyS1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-17T06:08:29Z"
    mac: ENC[AES256_GCM,data:YRKOoSbMpixGqGDekNSwOxk1OgUIp/7kL1v6JazroQwBZm1564BWGekPEztBoHBUebQqoDJtDTacE50s5Y63vw7XUaAv4zB5B+XOsfWBefp9qXJ1WNoMbVYfB3dQLJSY83xO5ryG0/PbwaLd5ifL56SEUEihwPDCZxoh0gtEDBY=,iv:vOxeOqnhW2Nae2w/Od6i9iyvfVHLxquUmbYi1YKlp5k=,tag:xDESX0vttj4DriUqUSkJ2Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
